apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-www-config
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: website
    app.kubernetes.io/part-of: guestbook
    app/language: javascript
data:
  API_URL: "https://api.dev.guestbook"
