apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "AppCtx.wwwName" . }}
  labels: {{ include "AppCtx.wwwLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.www.replicaCount }}
  selector:
    matchLabels: {{ include "AppCtx.wwwSelectorLabels" . | nindent 8 }}
  template:
    metadata:
      labels: {{ include "AppCtx.wwwLabels" . | nindent 10 }}
      annotations:
        checksum/config:
          {
            {
              include (print $.Template.BasePath "/www.config.yaml") . | sha256sum,
            },
          }
    spec:
      imagePullSecrets:
        - name: {{ .Values.registry.secretName }}
      containers:
        - name: guestbook-ui
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "300m"
